### ISSUE TITLE
Missing rapidjson dependency/directory

### ISSUE THREAD

**Issue by avislash** [jannotti/cpp-algorand-sdk#1]
The README should be updated to include project dependencies so users know that they need to brew install 

- libsodium
- msgpack
- openssl v1.1
- rapidjson
- curl (currently missing from the Makefile but is needed).

**Comment by jannotti** [comment]
I agree in spirit, though I'd rather the README references the Makefile, rather than names the dependencies explicitly, so there is less repetition.

**Comment by avislash** [comment]
A simple setup instruction to do a "make brew-deps" or "make deps" also works

**Comment by jannotti** [comment]
I'll add some explanation.  I don't recall the exact curl package I needed to install.  It was probably `libcurl` or of `libcurl-dev` or maybe it had a version number.  If you recently did this and recall, please let me know or make a PR.  I'm going to close this with just the README issue addressed.
