### ISSUE TITLE
Add environment setup instructions to README

### ISSUE THREAD

**Issue by avislash** [jannotti/cpp-algorand-sdk#2]
I recommend adding a section for environment setup to the README that explains the values in .env should be set in the environment the executable is running. I had mistakenly thought the .env file was where values should be set.

**Comment by jannotti** [comment]
I recently renamed `.env` to `.env.sandbox` to avoid confusion. It's not that you must point to any particular ALGOD_ADDRESS for things to work, but like all Algorand SDKs, you must set up environment variables to *some* algod.  The variables in `.env.sandbox` are the addresses and tokens that the algorand/sandbox use by default.  With them in there, it's possible to use the `dotenv` tool to set the variables easily on the command line when invoking an SDK program.

Unfortunately there are at least three different dotenv tools, all with different syntax (the js, python, and ruby worlds all have one, there are probably more as well.)

At any rate, I add some explanation to the README.  Thanks.

**Comment by avislash** [comment]
Gotcha. In the Python SDK the Algod Client Constructor accepts parameters for the node address and API key. Would you accept a PR that added an args constructor that took these as input arguments?

**Comment by jannotti** [comment]
That makes sense. I just added those constructors for AlgodClient and
IndexerClient.
