### ISSUE TITLE
Add Multisig functionality

### ISSUE THREAD

**Issue by avislash** [jannotti/cpp-algorand-sdk#3]
I'm still relatively new to the Algorand protocol/blockchain development, however, I'd like to help finish implementing the Multisig class definition. 

I have a basic understanding from https://developer.algorand.org/docs/features/transactions/signatures/ and it looks like the portion for adding the public addresses and threshold is already taken care of in the constructor. It looks like what needs to be added is the ability to add the sub signatures to sign the transactions and then add those sub signtaures to msgpack. 

Let me know if I'm on the right track and if there's anything you recommend I take a look t it. 

Thanks!

**Comment by jannotti** [comment]
That sounds right.  I'd certainly accept a PR to finish that off.

When in doubt, a very useful thing to do is check another Algorand SDK to see how things work, and/or to get some nice tests that can be adapted for use here.

Of course, go-algorand code is useful too. Especially `crypto/multisig.go`

**Comment by avislash** [comment]
Awesome, I'll give the implementation a shot and add a unit test to examples.cpp as part of the PR when I get it working!

**Comment by avislash** [comment]
Hi John, 

I made some updates to be able to add signatures to the Multisig subsigs. I updated the original sign(Account) method to take in a vector of accounts since this is a MultiSig object (it made more sense to me to be able to pass in a collection of 1 or more accounts and get back an object that contained all of them).   

Feel free to take  a look at  my latest commit (0975302)  and let me know if this is headed in the right direction and any other comments you might have.

Also a question I have, the signature in the SubSigs should be the 64 byte signature (32-byte SK + 32-byte PK) and not the 32 byte SK correct?

**Comment by jannotti** [comment]
I think you are on the right track, though I can't speak to confidently
about the structure of multisigs - that's why I put off working on them.

It would be great to have all of your changes in a PR (which you can mark
"in progress" if you aren't actually prepared to have it considered for
merge).  That way I can see all changes as a whole, instead of commit by
commit.

**Comment by avislash** [comment]
Thanks for the feedback, I was mainly looking to get some feedback on that the changes/design decisions I was making were in line with the vision you had for the SDK. I'll work on getting the rest of the multisig functionality added/tested and I'll throw up an in progress PR/comment back if I run into issues or have questions.

**Comment by avislash** [comment]
@jannotti I was able to get MultSig transactions working. I just need to do some cleanup but then the code will be ready for a PR. Unfortunately, before I can do a PR I think I need to get approval from my organization due to IP agreements so it'll still be a few days out. Thanks!

**Comment by jannotti** [comment]
Thanks @avislash
